[package]
name = "rust-hello-world"
version = "0.1.0"
authors = ["Jesse Schmucker <Jesse@Marissas-MacBook-Pro.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.1.1"